### PR TITLE
Update tests to triava cache v1.0.4

### PR DESCRIPTION
**Pull request by christian-esken**
Update to triava v1.0.4
- Follow last API changes between 0.9.5 and 1.0
- Fix omissions for triava in the JMH tests

README updates

### CODE REVIEW

**Comment by christian-esken** [comment]
Side note. The README should also reflect that running as root may be required, as it writes to an output directory /run/shm/jmh-result/ . That directory could not be created as ordinary user for me so the test run failed. Also running as root is beneficial for not interrupting the test with entering passwords for limitCoreCount.sh.

I propose this addition. I did not commit that, as I was not sure where the best position in the README woiuld be.
> This  should be run as root, for writing to the output directory /run/shm/jmh-result/ , and to limit the core count via ./limitCoreCount.sh

**Comment by cruftex** [comment]
Hi Christian,

thanks for the update. I am in vacation for two weeks and need to look into that later.

I am a little clueless about the shell "glue code". Depending on the environment and the benchmark aims, there will always need to be some modifications necessary. I see the jmh-run.sh more as an example rather then something that should run OOTB.

**Comment by christian-esken** [comment]
OK. A small hint in the README would be sufficent then. Lets discuss details later. Have a nice vacation.

**Comment by cruftex** [comment]
Closing outdated PR

**Pull request closed without merging**
